#!/usr/bin/env python3
"""Generate the learning and review menu entries from selected docs/ files.

The generated module is used by the SPA routes, the learning sidebar, and the
learning sidebar. Run this after changing docs; Dockerfile runs it too so a
push always deploys the exact document set bundled in the image.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
INDEX_HTML = ROOT / "app" / "frontend" / "index.html"
OUT_MODULE = ROOT / "app" / "frontend" / "js" / "data" / "learnDocs.js"
LEARN_DOCS = (
    ("03", "주식 1"),
    ("05", "주식 2"),
    ("04", "주식 3"),
    ("06", "주식 4"),
    ("07", "주식 5"),
)
REVIEW_DOCS = (
    ("10-1", "법인과 회사 구조 1: 시작하기"),
    ("10-2", "법인과 회사 구조 2: 운영·자금"),
    ("10-3", "법인과 회사 구조 3: 세무·회계"),
    ("11", "거시경제와 주식시장"),
)


def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return re.sub(r"^(?:Day|DAY)\s+\d+\s*[—-]\s*", "", match.group(1)).strip()
    return path.stem


HOT_DOCS = {"05"}


def menu_html(docs: list[dict[str, str]]) -> str:
    rows = []
    for doc in docs:
        icon = "fa-spell-check" if doc["id"] == "voca" else "fa-circle-dot"
        badge = '<span class="nav-badge-hot">HOT</span>' if doc["id"] in HOT_DOCS else ""
        rows.append(
            f'            <a class="nav-item" data-view="learn-{html.escape(doc["id"])}">'
            f'<i class="fa-solid {icon}"></i>{html.escape(doc["label"])}{badge}</a>'
        )
    return "\n".join(rows)


def main() -> None:
    def load_docs(entries: tuple[tuple[str, str], ...]) -> list[dict[str, str]]:
        docs = []
        for doc_id, label in entries:
            path = DOCS_DIR / f"{doc_id}.md"
            title = title_for(path)
            docs.append({"id": doc_id, "file": path.name, "title": title, "label": label})
        return docs

    learn_docs = load_docs(LEARN_DOCS)
    review_docs = load_docs(REVIEW_DOCS)
    docs = [*learn_docs, *review_docs]

    OUT_MODULE.write_text(
        "// Generated by scripts/sync_learning_menu.py from docs/*.md. Do not edit manually.\n"
        f"export const LEARN_DOCS = {json.dumps(docs, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )

    source = INDEX_HTML.read_text(encoding="utf-8")
    replacements = {
        "learn": menu_html(learn_docs),
        "review": menu_html(review_docs),
    }
    for section_id, rows in replacements.items():
        replacement = f'<div class="nav-children" id="nav-{section_id}">\n{rows}\n          </div>'
        source, count = re.subn(
            rf'<div class="nav-children" id="nav-{section_id}">.*?</div>',
            replacement,
            source,
            count=1,
            flags=re.S,
        )
        if count != 1:
            raise SystemExit(f"index.html에서 {section_id} 학습 메뉴를 찾지 못했습니다.")

    INDEX_HTML.write_text(source, encoding="utf-8")
    print(f"학습 메뉴 동기화 완료: 일반 {len(learn_docs)}개, 지난주 정리 {len(review_docs)}개")


if __name__ == "__main__":
    main()
